### PR TITLE
WIP: EasyAdminBundle setup

### PR DESCRIPTION
**Pull request by kochen**
Setup EasyAdminBundle and see how much we can get "out-of-the-box" - solves #24

- [ ] fix entity delete
- [ ] fix entity edit
- [ ] tweak config (translations, columns)

### CODE REVIEW

**Comment by ro0NL** [comment]
Nice :+1: i'll try to play with it ASAP and see if I can collaborate.

**Comment by ro0NL** [comment]
@kochen i think we should require dev-master for it.. aka 2.0. Basically embeddables are not handled AFAIK and 1.x will not receive any updates.

**Comment by ro0NL** [comment]
@kochen let's close.. im not sure we should go down this road, and it's not a requirement for the demo app to me anyway :)

Basically as explained in https://github.com/msgphp/symfony-demo-app/issues/24#issuecomment-385242740

**Comment by kochen** [comment]
Makes sense to me.

**Pull request closed without merging**
