### PR TITLE
release fixes

### PR DESCRIPTION
**Pull request by ro0NL**
after https://github.com/msgphp/msgphp/pull/13

### CODE REVIEW

**Comment by Evertt** [comment]
Hey @ro0NL, I want to say I really like your library. I'll be working on my first Symfony project soon and I'm eager to use your library instead of FOSUserBundle.

I basically have two questions:

1. Do you know, roughly, when msgphp/msgphp#13 and this PR will be merged?
2. Since I never used Symfony before I not sure about this one thing. For my project, I want to have multiple user entities (`Consumer`, `Supplier`, and `Admin`) which are all connected to one abstract `BaseUser` class through Doctrine's single-table-inheritance. Do you know if it's possible to do that and still be able to use all of those user entities as authenticatible user entities? The reason I want to use different entities rather than just user-roles is that `Consumer` and `Supplier` probably need to fill in very different information during registration. And I like being able to give them different class methods as well, for different abilities.

**Comment by ro0NL** [comment]
Hi @Evertt, cool :+1: We're close to 0.1 release. Aiming for this week or so, ill try to announce it here and there. The base domain layer wil be working (you can use our entities). The message infra (domain commands/events) might be postponed a bit.

> I want to have multiple user entities

Yep, it's on my list. As a matter of fact creating a ticket for it now!e Ill need to dive into it a bit to see the technical side, but in general should be possible yes :)

**Comment by Evertt** [comment]
>> I want to have multiple user entities
>
> Yep, it's on my list. As a matter of fact creating a ticket for it now!e Ill need to dive into it a bit to see the technical side, but in general should be possible yes :)

So that could more than a month or so? I'm considering to try to contribute, because I need this functionality soonish (as in I have a paid project for which I'd like to use this and that project could start anywhere between next week and in a few weeks). Unfortunately I don't think I can write my code as beautiful as you do, so I'm not sure my contribution would actually help.

**Comment by ro0NL** [comment]
> So that could more than a month or so?

I guess =/ now working on the 0.1 release (domain only) next is all message infra (see https://github.com/msgphp/msgphp/pull/42). Given that is broken i need to clean up related things in the demo app as well (after this PR). Meaning you'll be left with a basic login/logout + our base user domain.

> because I need this functionality soonish (as in I have a paid project for which I'd like to use this

In general we dont rush things :) so currently you need to decide if it fits your needs as-is (it's a new project really). From our side the base user domain (entity design and such) will be solid (the current state, but no real promises before `1.0` ;-)). Ill also post a blog soon-ish about the current state :+1:

**Pull request merged**
